/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShortWeight */

#ifndef _Included_ShortWeight
#define _Included_ShortWeight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShortWeight
 * Method:    matrixWeight
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_ShortWeight_matrixWeight
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
